<a href="https://colab.research.google.com/github/Rohit1208/machine_learning/blob/main/covid_19_project(1).ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import pandas as pd
import  numpy as np

In [ ]:
df =pd.read_excel("/content/world covid transmissio calssification.xlsx")

In [ ]:
df

Name  ... Transmission Classification
0                      Global  ...                         NaN
1    United States of America  ...      Community transmission
2                       India  ...           Clusters of cases
3                      Brazil  ...      Community transmission
4                      France  ...      Community transmission
..                        ...  ...                         ...
219           Solomon Islands  ...                    No cases
220                      Saba  ...                    No cases
221          Marshall Islands  ...                    No cases
222                   Vanuatu  ...                    No cases
223                     Samoa  ...                    No cases

[224 rows x 13 columns]

In [ ]:
df.head(10)


Name  ... Transmission Classification
0                    Global  ...                         NaN
1  United States of America  ...      Community transmission
2                     India  ...           Clusters of cases
3                    Brazil  ...      Community transmission
4                    France  ...      Community transmission
5                    Turkey  ...      Community transmission
6        Russian Federation  ...           Clusters of cases
7        The United Kingdom  ...      Community transmission
8                     Italy  ...           Clusters of cases
9                 Argentina  ...      Community transmission

[10 rows x 13 columns]

In [ ]:
df.shape

(224, 13)

In [ ]:
df.iloc[5,2:11].values

array([5354153, 6348.37, 41055, 48.68, 5904, 49012, 58.11, 488, 0.58],
      dtype=object)

In [ ]:
x = df.iloc[1:,2:11].values
y = df.iloc[1:,-1].values

In [ ]:
x

array([[3.3175399e+07, 1.0022700e+04, 8.0434000e+04, ..., 1.7994000e+02,
        2.2260000e+03, 6.7000000e-01],
       [2.9762793e+07, 2.1567200e+03, 4.8797000e+05, ..., 2.7790000e+01,
        2.0411000e+04, 1.4800000e+00],
       [1.7628588e+07, 8.2934900e+03, 5.0571100e+05, ..., 2.3226000e+02,
        1.4178000e+04, 6.6700000e+00],
       ...,
       [4.0000000e+00, 6.7600000e+00, 0.0000000e+00, ..., 0.0000000e+00,
        0.0000000e+00, 0.0000000e+00],
       [3.0000000e+00, 9.8000000e-01, 0.0000000e+00, ..., 0.0000000e+00,
        0.0000000e+00, 0.0000000e+00],
       [1.0000000e+00, 5.0000000e-01, 0.0000000e+00, ..., 0.0000000e+00,
        0.0000000e+00, 0.0000000e+00]])

In [ ]:
y

array(['Community transmission', 'Clusters of cases',
       'Community transmission', 'Community transmission',
       'Community transmission', 'Clusters of cases',
       'Community transmission', 'Clusters of cases',
       'Community transmission', 'Community transmission',
       'Community transmission', 'Community transmission',
       'Community transmission', 'Community transmission',
       'Community transmission', 'Community transmission',
       'Community transmission', 'Community transmission',
       'Community transmission', 'Community transmission',
       'Community transmission', 'Community transmission',
       'Community transmission', 'Community transmission',
       'Community transmission', 'Community transmission',
       'Community transmission', 'Community transmission',
       'Community transmission', 'Clusters of cases',
       'Community transmission', 'Community transmission',
       'Community transmission', 'Clusters of cases',
       'Community tran

In [ ]:
from sklearn.preprocessing import LabelEncoder

In [ ]:
le = LabelEncoder()

In [ ]:
y=le.fit_transform(y)

In [ ]:
y

array([1, 0, 1, 1, 1, 0, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       0, 1, 0, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 0,
       1, 1, 1, 0, 1, 1, 1, 1, 0, 1, 1, 0, 1, 1, 1, 1, 1, 5, 0, 0, 1, 1,
       1, 0, 0, 0, 1, 0, 0, 1, 0, 0, 1, 1, 0, 0, 1, 1, 0, 1, 0, 1, 1, 1,
       1, 5, 1, 1, 1, 1, 1, 5, 1, 1, 0, 1, 1, 0, 0, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 5, 1, 1, 1, 1, 1, 1, 1, 1, 1, 4, 1, 1, 1, 1, 1, 0, 0, 1,
       0, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1,
       1, 1, 1, 1, 5, 1, 1, 5, 5, 0, 1, 5, 1, 1, 5, 0, 0, 1, 2, 5, 0, 0,
       1, 3, 5, 5, 4, 5, 0, 5, 0, 0, 4, 2, 5, 0, 5, 2, 5, 5, 2, 2, 2, 2,
       2, 2, 2])

In [ ]:
from sklearn.model_selection import train_test_split

In [ ]:
x_train,x_test,y_train,y_test = train_test_split(x,y,test_size=0.2)

In [ ]:
x_test.shape

(45, 9)

In [ ]:
from sklearn.preprocessing import StandardScaler

In [ ]:
sc = StandardScaler()

In [ ]:
x_train=sc.fit_transform(x_train)
x_test = sc.fit_transform(x_test)

In [ ]:
x_test

array([[-3.26971545e-01, -5.30627737e-01, -2.97272702e-01,
        -6.57679082e-01, -2.83516366e-01, -3.41211199e-01,
        -8.67178181e-01, -2.59057006e-01, -4.97348267e-01],
       [-3.23306818e-01, -3.75439609e-01, -2.89054136e-01,
         5.61419404e-01, -2.75932581e-01, -3.36470408e-01,
        -8.45958945e-02, -2.53008269e-01,  9.15129984e-01],
       [-2.61116232e-01,  1.12699325e+00, -1.92647375e-01,
         2.20071062e+00, -1.85993635e-01, -3.21273898e-01,
        -2.61094970e-01, -2.50258844e-01, -1.19005879e-01],
       [-3.26519046e-01, -7.32388280e-01, -2.97234163e-01,
        -6.37107849e-01, -2.83457118e-01, -3.40810722e-01,
        -6.29972417e-01, -2.59057006e-01, -4.97348267e-01],
       [-3.25974708e-01, -1.01704585e+00, -2.95866007e-01,
        -6.43852515e-01, -2.82153655e-01, -3.41124610e-01,
        -8.66194508e-01, -2.59057006e-01, -4.97348267e-01],
       [-3.26544864e-01,  5.58730438e-01, -2.96164689e-01,
         2.68621420e+00, -2.83516366e-01, -3.409406

In [ ]:
import tensorflow as tf

In [ ]:
ann= tf.keras.models.Sequential()

In [ ]:
ann.add(tf.keras.layers.Dense(units=6, activation='relu'))

In [ ]:
ann.add(tf.keras.layers.Dense(units=6,activation="relu"))

In [ ]:
ann.add(tf.keras.layers.Dense(units=6,activation="relu"))

In [ ]:
ann.add(tf.keras.layers.Dense(units=1, activation='sigmoid'))

In [ ]:
ann.compile?

In [ ]:
ann.compile(optimizer="rmsprop",loss="categorical_crossentropy",metrics=['accuracy', 'mse'])

In [ ]:

ann.fit(x_train, y_train, batch_size= 32, epochs= 200)

Epoch 1/200
6/6 [==============================] - 1s 3ms/step - loss: 0.0000e+00 - accuracy: 0.6966 - mse: 1.5776
Epoch 2/200
6/6 [==============================] - 0s 2ms/step - loss: 0.0000e+00 - accuracy: 0.6966 - mse: 1.5725
Epoch 3/200
6/6 [==============================] - 0s 2ms/step - loss: 0.0000e+00 - accuracy: 0.6966 - mse: 1.5694
Epoch 4/200
6/6 [==============================] - 0s 2ms/step - loss: 0.0000e+00 - accuracy: 0.6966 - mse: 1.5671
Epoch 5/200
6/6 [==============================] - 0s 2ms/step - loss: 0.0000e+00 - accuracy: 0.6966 - mse: 1.5647
Epoch 6/200
6/6 [==============================] - 0s 2ms/step - loss: 0.0000e+00 - accuracy: 0.6966 - mse: 1.5624
Epoch 7/200
6/6 [==============================] - 0s 3ms/step - loss: 0.0000e+00 - accuracy: 0.6966 - mse: 1.5605
Epoch 8/200
6/6 [==============================] - 0s 2ms/step - loss: 0.0000e+00 - accuracy: 0.6966 - mse: 1.5587
Epoch 9/200
6/6 [==============================] - 0s 2ms/step - loss: 0.0000e+0

In [ ]:
y_pred=ann.predict([x_test])

Consider rewriting this model with the Functional API.


In [ ]:
y_pred

array([[1.        ],
       [0.99995613],
       [0.98625964],
       [1.        ],
       [1.        ],
       [0.9737953 ],
       [1.        ],
       [1.        ],
       [1.        ],
       [1.        ],
       [1.        ],
       [0.99999756],
       [0.9999993 ],
       [0.99813306],
       [0.99278224],
       [1.        ],
       [1.        ],
       [1.        ],
       [0.9999949 ],
       [1.        ],
       [1.        ],
       [0.81744623],
       [1.        ],
       [0.9916851 ],
       [       nan],
       [0.99999917],
       [1.        ],
       [0.7408386 ],
       [0.99999905],
       [1.        ],
       [0.99960196],
       [1.        ],
       [0.9876322 ],
       [1.        ],
       [0.999887  ],
       [1.        ],
       [1.        ],
       [1.        ],
       [1.        ],
       [1.        ],
       [1.        ],
       [1.        ],
       [0.7455225 ],
       [0.9999819 ],
       [1.        ]], dtype=float32)

In [ ]:
ann.predict([[5354153, 6348.37, 41055, 48.68, 5904, 49012, 58.11, 488, 0.58]])

array([[0.6936116]], dtype=float32)